version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # - VITE_BACKEND_URL=http://localhost:8000
        - VITE_BACKEND_URL=http://46.62.134.156/api:8000
    ports:
      - "3000:80"
    networks:
      - appnet

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    networks:
      - appnet

  jwttool-worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    volumes:
      - ./worker:/app
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
