name: Deploy JWT Security Checker

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # allow manual runs

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Hetzner
    
    environment:
      name: production
      url: https://xjwt.io

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}

    - name: Deploy to Hetzner
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
          set -e

          # move to project directory
          cd /root/jwt_pentest

          # update code
          git pull origin main

          # stop running containers
          docker-compose down

          # rebuild and restart containers
          docker-compose up -d --build

          # prune unused images
          docker image prune -f

          # confirm
          docker-compose ps
        EOF

    - name: Health Check
      run: |
        sleep 30
        curl -f https://xjwt.io || exit 1
        curl -f https://xjwt.io/api/decode -X POST -H "Content-Type: application/json" -d '{"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"}' || echo "API check failed"