jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Hetzner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Sync code to server
      run: |
        rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/root/jwt_pentest/

    - name: Deploy on Hetzner
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
          set -e
          cd /root/jwt_pentest
          docker-compose down
          docker-compose up -d --build
          docker image prune -f
          docker-compose ps
        EOF

    - name: Health Check
      run: |
        sleep 30
        curl -f https://xjwt.io || exit 1
        curl -f https://xjwt.io/api/decode -X POST -H "Content-Type: application/json" -d '{"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."}' || echo "API check failed"